[package]
name = "networktool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.8"
pnet = "0.27"
colored = "2.0.4"
